Repository ImpulsoGov/bd, pull requests merged in 2024-03, with the labels that each got.

#32 Regra de vinculação - ajustes transmissões e listas unificadas
  bd_analitico/esus-backups/impulso_previne_dados_nominais/funcoes/consulta_tabelas_lista_nominal_diabeticos.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/funcoes/consulta_tabelas_lista_nominal_hipertensos.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/funcoes/unir_tabelas_lista_nominal_vacinacao.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/eventos_vacinacao.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/lista_nominal_diabeticos_unificada.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/lista_nominal_hipertensos_unificada.sql
  transmissor_impulso_esus/codigos_listas_transmitidas/lista_nominal_diabeticos.sql
  transmissor_impulso_esus/codigos_listas_transmitidas/lista_nominal_hipertensos.sql
  transmissor_impulso_esus/codigos_listas_transmitidas/lista_nominal_vacinacao.sql
  transmissor_impulso_esus/ddls_tabelas_transmitidas/diabeticos.sql
  transmissor_impulso_esus/ddls_tabelas_transmitidas/hipertensos.sql
  transmissor_impulso_esus/ddls_tabelas_transmitidas/vacinacao.sql
  validacoes_listas_nominais/validacoes_ajustes_lista_nominal_vacinacao.sql
Labels: enhancement

#33 Corrige cálculo da data de produção mais recente no painel de vacinação
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_vacinacao_lista_nominal.sql
Labels: bug

#35 Ajustes regras de vinculação - painel de vacinação
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/lista_nominal_vacinacao_unificada.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_vacinacao_lista_nominal.sql
  validacoes_listas_nominais/validacoes_ajustes_lista_nominal_vacinacao.sql
Labels: bug, enhancement

#36 Ajustes regras de vinculação - painel de hipertensão
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/api_futuro_painel_hipertensos_lista_nominal.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_enfermeiras_lista_nominal_hipertensos.sql
  validacoes_listas_nominais/validacoes_ajustes_lista_nominal_hipertensao.sql
Labels: bug, enhancement

#37 Ajustes regras de vinculação - painel de diabetes
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/api_futuro_painel_diabeticos_lista_nominal.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_enfermeiras_lista_nominal_diabeticos.sql
  validacoes_listas_nominais/validacoes_ajustes_lista_nominal_diabetes.sql
Labels: bug, enhancement

#34 Ajustes regras de vinculação - painel de citopatológico
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_citopatologico_lista_nominal.sql
Labels: bug, enhancement

#42 Corrige nome do município de demo para Bonfim - RR
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_citopatologico_lista_nominal.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_enfermeiras_lista_nominal_diabeticos.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_enfermeiras_lista_nominal_hipertensos.sql
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_vacinacao_lista_nominal.sql
Labels: enhancement

#43 Corrige cláusula que traz o ine do último cadastro e corrige ordenação da seleção final.
  bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_gestantes_lista_nominal.sql
Labels: bug
